### PR TITLE
Add font, set colors

### PR DESCRIPTION
**Pull request by Huntsekkern**
I tried to improve what we have as generalisation of styles and themes.
For colours, I selected colours very close to EPFL guidelines for their own branding.
For font, Roboto is a modern classic which is very agreeable.
But feel free to change any of those, I don't care.

The impact this PR has on your code:
When using a button, you should set its style to Button.
You should **never** hardcode a colour. Either pick one from colourPrimary, colourPrimaryVariant, colourSecondary, colourSecondaryVariant, etc, or you may consider creating a style if you're designing a reusable UI element (such as a button).
You should not hardcode a font, so it default to the common font.

I did not update xml existing files (a bit to try out, but I did not focus on that, I believe each of us should update their own files so we get used to using styles and resources for futures activities).

### CODE REVIEW

**Review by Snowflake8 — APPROVED** [review]
Only touches the xml, and is as discussed
I see no reason not to approve the current version

**Review by so7fie — COMMENTED** [review]
Ce serait bien de mettre les strings dans un fichiers au clieu de hardcoder. Et pour ceux que tu ne sais pas encore au lieu de mettre "textView", tu peux ajouter une variable genre "todo" à ton fichier de strings

**Review by Laniakea1999 — COMMENTED** [review]
Ok but we have to pay attention and fix the warnings for xml files.

**Comment by Huntsekkern** [comment]
> Ok but we have to pay attention and fix the warnings for xml files.

I'm sorry Zied, but those are your warnings from your files that we've been telling you to fix for 2 weeks!

Et ça répond aussi au passage au même commentaire de @so7fie

**Comment by Huntsekkern** [comment]
> Ok but we have to pay attention and fix the warnings for xml files.

> Ce serait bien de mettre les strings dans un fichiers au clieu de hardcoder (ça calmerait un peu code climate). Et pour ceux que tu ne sais pas encore au lieu de mettre "textView", tu peux ajouter une variable genre "todo" à ton fichier de strings

Very good idea on the todo variable for the fill-sale-activity. Technically, it's not that I still don't know their name, it's that they will be auto-filled later, but I'm fine on using a temporarily todo placeholder to reduce the warnings amount.

However regarding all the warnings from activity-main, activity-login and activity-register, they come from @Laniakea1999 and I've been telling him for 2 weeks to fix the warnings on his files, so I'm kind of annoyed that now he comes and say on my PR that we have to fix his warnings.

**Review by so7fie — APPROVED** [review]

**Comment by Laniakea1999** [comment]
> > Ok but we have to pay attention and fix the warnings for xml files.
> 
> > Ce serait bien de mettre les strings dans un fichiers au clieu de hardcoder (ça calmerait un peu code climate). Et pour ceux que tu ne sais pas encore au lieu de mettre "textView", tu peux ajouter une variable genre "todo" à ton fichier de strings
> 
> Very good idea on the todo variable for the fill-sale-activity. Technically, it's not that I still don't know their name, it's that they will be auto-filled later, but I'm fine on using a temporarily todo placeholder to reduce the warnings amount.
> 
> However regarding all the warnings from activity-main, activity-login and activity-register, they come from @Laniakea1999 and I've been telling him for 2 weeks to fix the warnings on his files, so I'm kind of annoyed that now he comes and say on my PR that we have to fix his warnings.

I am not telling you to fix the warnings of my code, all my warnings are already fixed in my local branch. From the changes that you made, I thought I saw more warnings coming from your code and that's what I'm gently asking you to fix if there exist any and It was also a message to be careful about these warnings for futur xml files that will be created. Also you didn't "tell me for 2 weeks to fix the warnings on my files", we talked about this once 2 weeks ago and I told you that I will do it after completing other tasks (which I did).

**Comment by Huntsekkern** [comment]
> I am not telling you to fix the warnings of my code, all my warnings are already fixed in my local branch. From the changes that you made, I thought I saw more warnings coming from your code and that's what I'm gently asking you to fix if there exist any and It was also a message to be careful about these warnings for futur xml files that will be created. Also you didn't "tell me for 2 weeks to fix the warnings on my files", we talked about this once 2 weeks ago and I told you that I will do it after completing other tasks (which I did).

Fair enough, thanks for answering. When I wrote my message, I had no way to know that you already fixed your warnings on your local branch.

I just want to clarify the "tell me for 2 weeks to fix the warnings on my files", as I don't want to sound like I was lying:
I first told it to you explicitly in a meeting 2 weeks ago which is the time you recall.
Then, I wrote in a PR comment 8 days ago that "everyone should fix their own warnings". I clearly had you in mind when I wrote that comment, but I did not want to make you feel attacked, so I didn't tag you. It wasn't on one of your PR, so maybe you've never seen that comment. 
Then I said in our TA meeting 4 days ago that I didn't feel comfortable approving last-minute PRs because they were lacking tests and had warnings, again with your PR in mind, and again it's possible that I didn't mention you by name to not target the blame on you.

As I didn't explicitly mention you the last 2 times, I can perfectly understand why from your point of view, I only told you once and you felt no rush to do it.
And I hope you understand that from my point of view, it felt like I told you several times, you didn't fix it (as I'm not seeing your local branch before you PR it) and then came to tell me to fix warnings.
I hope that solves the argument. 

Regarding my warnings, I thought they were fine as they only applied to temporary placeholders while each of my definitive items had no warnings, but I realize this is not the correct approach and I should adopt Sophie suggestion so that the code looks cleaner. I won't merge it into this PR though as my next task for the week precisely concerns the activity which raises the majority of my warnings, so it'll be more coherent to do it on this one.

**Comment by Laniakea1999** [comment]
> Fair enough, thanks for answering. When I wrote my message, I had no way to know that you already fixed your warnings on your local branch.
> 
> I just want to clarify the "tell me for 2 weeks to fix the warnings on my files", as I don't want to sound like I was lying:
> I first told it to you explicitly in a meeting 2 weeks ago which is the time you recall.
> Then, I wrote in a PR comment 8 days ago that "everyone should fix their own warnings". I clearly had you in mind when I wrote that comment, but I did not want to make you feel attacked, so I didn't tag you. It wasn't on one of your PR, so maybe you've never seen that comment.
> Then I said in our TA meeting 4 days ago that I didn't feel comfortable approving last-minute PRs because they were lacking tests and had warnings, again with your PR in mind, and again it's possible that I didn't mention you by name to not target the blame on you.
> 
> As I didn't explicitly mention you the last 2 times, I can perfectly understand why from your point of view, I only told you once and you felt no rush to do it.
> And I hope you understand that from my point of view, it felt like I told you several times, you didn't fix it (as I'm not seeing your local branch before you PR it) and then came to tell me to fix warnings.
> I hope that solves the argument.
> 
> Regarding my warnings, I thought they were fine as they only applied to temporary placeholders while each of my definitive items had no warnings, but I realize this is not the correct approach and I should adopt Sophie suggestion so that the code looks cleaner. I won't merge it into this PR though as my next task for the week precisely concerns the activity which raises the majority of my warnings, so it'll be more coherent to do it on this one.

All right, It was just a misunderstanding then. Problem solved.

**Pull request merged**
